version: '3.11'

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=demo_blog_dj
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=admin

  web:
    build: .
    command: bash -c "python blogblog/manage.py migrate && python blogblog/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
