# Generated by Django 4.2 on 2023-05-09 07:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
