# Generated by Django 4.2 on 2023-05-22 08:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_time_last_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text (maximum 2000 characters)'),
        ),
    ]
